server:
  port: 8082

spring:
  application:
    name: Education-Service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    root: info
    org.andarworld.courseservice: debug