server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: Education-Service

resilience4j:
  circuitbreaker:
    configs:
      default:
        record-exceptions:
          - org.andarworld.educationservice.api.exceptions.GeneralException
        failure-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        max-wait-duration-in-half-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 10
    instances:
      university-service:
        base-config: default
      course-service:
        base-config: default
    circuit-breaker-aspect-order: 1
  retry:
    configs:
      default:
        retry-exceptions:
          - org.andarworld.educationservice.api.exceptions.GeneralException
        max-attempts: 3
        wait-duration: 2s
        event-consumer-buffer-size: 10
    instances:
      university-service:
        base-config: default
      course-service:
        base-config: default
    retry-aspect-order: 2


management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, retryevents, retries, health
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    root: info
    org.andarworld.courseservice: debug
    io.github.resilience4j: debug
    org.springframework.cloud.openfeign: debug
    feign: debug
