from:
  config:
    application: from_application_yml
    educationservice: from_education_service

server:
  port: ${SERVER_PORT:0}

spring:
  profiles:
    active: ${PROFILES:default}
  application:
    name: EDUCATION-SERVICE
  config:
    import: configserver:http://localhost:8787

resilience4j:
  circuitbreaker:
    configs:
      default:
        record-exceptions:
          - org.andarworld.educationservice.api.exceptions.GeneralException
        failure-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        max-wait-duration-in-half-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 10
    instances:
      university-service:
        base-config: default
      course-service:
        base-config: default
    circuit-breaker-aspect-order: 1
  retry:
    configs:
      default:
        retry-exceptions:
          - org.andarworld.educationservice.api.exceptions.GeneralException
        max-attempts: 3
        wait-duration: 1s
        event-consumer-buffer-size: 10
    instances:
      university-service:
        base-config: default
      course-service:
        base-config: default
    retry-aspect-order: 2

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, retryevents, retries, health, env
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.andarworld.educationservice: debug
    io.github.resilience4j: debug
    org.springframework.cloud.openfeign: debug
    feign: debug